export type ImageName =
  | 'AddLock'
  | 'Add'
  | 'AppIcon'
  | 'AppIconCopy'
  | 'Archive'
  | 'Archived'
  | 'ArrowDownRightThicker'
  | 'ArrowLeft'
  | 'ArrowRight'
  | 'AtoZ'
  | 'Back'
  | 'Backup'
  | 'BaseIcon'
  | 'BaseIcon40'
  | 'BaseIcon40Copy'
  | 'Camera'
  | 'Cancel'
  | 'Change'
  | 'CheckedOff'
  | 'Checked'
  | 'CheckedUnchecked'
  | 'CloudOffline'
  | 'Cold'
  | 'Copy'
  | 'Dev'
  | 'Done'
  | 'DoubleDownChevron'
  | 'DoubleUpChevron'
  | 'DownChevron'
  | 'Down'
  | 'DownloadFiles'
  | 'Download'
  | 'Drag'
  | 'Edit'
  | 'Eraser'
  | 'ExerciseFilled'
  | 'Exercise'
  | 'Explode'
  | 'File'
  | 'Fingerprint'
  | 'GroceryFilled'
  | 'Grocery'
  | 'Hide'
  | 'High'
  | 'Home'
  | 'ImageFilled'
  | 'Image'
  | 'Info'
  | 'InProgress'
  | 'Insert'
  | 'Ladybug'
  | 'LadybugGreen'
  | 'LadybugYellow'
  | 'LeftHand'
  | 'Link'
  | 'List'
  | 'LocationFilled'
  | 'Location'
  | 'Log'
  | 'Low'
  | 'Med'
  | 'MedicineFilled'
  | 'Medicine'
  | 'Menu'
  | 'MenuAlt'
  | 'Minus'
  | 'Move'
  | 'NewFile'
  | 'Next'
  | 'Note'
  | 'Null'
  | 'Palette'
  | 'PenIbFilled'
  | 'Pin'
  | 'Question'
  | 'QuestionFilled'
  | 'QuestionMark'
  | 'QuestionThick'
  | 'QuestionThicker'
  | 'Refresh'
  | 'Review'
  | 'RightHand'
  | 'Save'
  | 'Search'
  | 'Show'
  | 'SlimPin'
  | 'Sort'
  | 'StepFilled'
  | 'Step'
  | 'Stop'
  | 'Sync'
  | 'Tag'
  | 'TagNone'
  | 'TagSingle'
  | 'Theme'
  | 'ToBottom'
  | 'ToTop'
  | 'Trash'
  | 'Unarchive'
  | 'Unchecked'
  | 'UndoThicker'
  | 'Unlocked'
  | 'UpChevron'
  | 'Up'
  | 'Upload'
  | 'User'
  | 'Vibrate'
  | 'Wait'
  | 'Zero';

export const Images: Record<ImageName, any> = {
  AddLock: require('../public/images/add-lock.png'),
  Add: require('../public/images/add.png'),
  AppIcon: require('../public/images/appicon.png'),
  AppIconCopy: require('../public/images/appicon - Copy.png'),
  Archive: require('../public/images/archive.png'),
  Archived: require('../public/images/archived.png'),
  ArrowDownRightThicker: require('../public/images/arow-down-right-thicker.png'),
  ArrowLeft: require('../public/images/arrow-left.png'),
  ArrowRight: require('../public/images/arrow-right.png'),
  AtoZ: require('../public/images/atoz.png'),
  Back: require('../public/images/back.png'),
  Backup: require('../public/images/backup.png'),
  BaseIcon: require('../public/images/baseIcon.png'),
  BaseIcon40: require('../public/images/baseIcon40%.png'),
  BaseIcon40Copy: require('../public/images/baseIcon40% - Copy.png'),
  Camera: require('../public/images/camera.png'),
  Cancel: require('../public/images/cancel.png'),
  Change: require('../public/images/change.png'),
  CheckedOff: require('../public/images/checked-off.png'),
  Checked: require('../public/images/checked.png'),
  CheckedUnchecked: require('../public/images/checkedunchecked.png'),
  CloudOffline: require('../public/images/cloud-offline.png'),
  Cold: require('../public/images/cold.png'),
  Copy: require('../public/images/copy.png'),
  Dev: require('../public/images/dev.png'),
  Done: require('../public/images/done.png'),
  DoubleDownChevron: require('../public/images/doubledown-chevron.png'),
  DoubleUpChevron: require('../public/images/doubleup-chevron.png'),
  DownChevron: require('../public/images/down-chevron.png'),
  Down: require('../public/images/down.png'),
  DownloadFiles: require('../public/images/download-files.png'),
  Download: require('../public/images/download.png'),
  Drag: require('../public/images/drag.png'),
  Edit: require('../public/images/edit.png'),
  Eraser: require('../public/images/eraser.png'),
  ExerciseFilled: require('../public/images/exercise-filled.png'),
  Exercise: require('../public/images/exercise.png'),
  Explode: require('../public/images/explode.png'),
  File: require('../public/images/file.png'),
  Fingerprint: require('../public/images/fingerprint.png'),
  GroceryFilled: require('../public/images/grocery-filled.png'),
  Grocery: require('../public/images/grocery.png'),
  Hide: require('../public/images/hide.png'),
  High: require('../public/images/high.png'),
  Home: require('../public/images/home.png'),
  ImageFilled: require('../public/images/image-filled.png'),
  Image: require('../public/images/image.png'),
  Info: require('../public/images/info.png'),
  InProgress: require('../public/images/inprogress.png'),
  Insert: require('../public/images/insert.png'),
  Ladybug: require('../public/images/ladybug.png'),
  LadybugGreen: require('../public/images/ladybuggreen.png'),
  LadybugYellow: require('../public/images/ladybugyellow.png'),
  LeftHand: require('../public/images/lefthand.png'),
  Link: require('../public/images/link.png'),
  List: require('../public/images/list.png'),
  LocationFilled: require('../public/images/location-filled.png'),
  Location: require('../public/images/location.png'),
  Log: require('../public/images/log.png'),
  Low: require('../public/images/low.png'),
  Med: require('../public/images/med.png'),
  MedicineFilled: require('../public/images/medicine-filled.png'),
  Medicine: require('../public/images/medicine.png'),
  MenuAlt: require('../public/images/menu-.png'),
  Menu: require('../public/images/menu.png'),
  Minus: require('../public/images/minus.png'),
  Move: require('../public/images/move.png'),
  NewFile: require('../public/images/newfile.png'),
  Next: require('../public/images/next.png'),
  Note: require('../public/images/note.png'),
  Null: require('../public/images/null.png'),
  Palette: require('../public/images/palette.png'),
  PenIbFilled: require('../public/images/pen-ib-filled.png'),
  Pin: require('../public/images/pin.png'),
  Question: require('../public/images/question.png'),
  QuestionFilled: require('../public/images/questionfilled.png'),
  QuestionMark: require('../public/images/questionmark.png'),
  QuestionThick: require('../public/images/questionthick.png'),
  QuestionThicker: require('../public/images/questionthicker.png'),
  Refresh: require('../public/images/refresh.png'),
  Review: require('../public/images/review.png'),
  RightHand: require('../public/images/righthand.png'),
  Save: require('../public/images/save.png'),
  Search: require('../public/images/search.png'),
  Show: require('../public/images/show.png'),
  SlimPin: require('../public/images/slimPin.png'),
  Sort: require('../public/images/sort.png'),
  StepFilled: require('../public/images/step-filled.png'),
  Step: require('../public/images/step.png'),
  Stop: require('../public/images/stop.png'),
  Sync: require('../public/images/sync.png'),
  Tag: require('../public/images/tag.png'),
  TagNone: require('../public/images/tagnone.png'),
  TagSingle: require('../public/images/tagsingle.png'),
  Theme: require('../public/images/theme.png'),
  ToBottom: require('../public/images/to-bottom.png'),
  ToTop: require('../public/images/to-top.png'),
  Trash: require('../public/images/trash.png'),
  Unarchive: require('../public/images/unarchive.png'),
  Unchecked: require('../public/images/unchecked.png'),
  UndoThicker: require('../public/images/undo-thicker.png'),
  Unlocked: require('../public/images/unlocked.png'),
  UpChevron: require('../public/images/up-chevron.png'),
  Up: require('../public/images/up.png'),
  Upload: require('../public/images/upload.png'),
  User: require('../public/images/user.png'),
  Vibrate: require('../public/images/vibrate.png'),
  Wait: require('../public/images/wait.png'),
  Zero: require('../public/images/zero.png'),
};
